version: '3.7'
services: 
    app:
        container_name: fravon_api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        restart: always
        env_file: 
            - .env
        volumes:
            - .:/usr/src/app
